### ISSUE TITLE
Still possible to use API of client for NPM integration ?

### ISSUE THREAD

**Issue by DutchmanNL** [ddsol/speedtest.net#104]
A lot has changed as I see, for the previous version I created an native integration to the ioBroker iOT system.
By the switching to the cli method the current code and implementation will fail I assume ?

As I don't seen any possibility anymore to handle events  by API call to the NPM module

Is this true ? If not, please update the readme

**Comment by ddsol** [comment]
You can use probably just version 1.6.2.

Wherever this new module is not going to be compatible is where it's not going to be compatible, which is a lot of places. I understand people had managed to get this module to run in the browser, which is great, but that was never the intention of this module.

I don't know what ioBroker iOT is and am not inclined to go and familiarize myself with it as that would be considerable work. All I can say is that this module is and was always only intended to work in vanilla node.js.

**Comment by DutchmanNL** [comment]
Which is perfectly fine and running native great iobroker is based on nodjs but something I have to figure out.

So onli the flu from now no other integration at all, to bad it was nice integration:)

**Comment by ddsol** [comment]
You can use probably just version 1.6.2. Because it's still the same as it was before. This is mostly due to it not having changed. The Git system actually provides strong assurances that prior versions, current versions, and possibly future versions have not changed.

That is to say that if it worked for you in a 1.x.x version then it should still work in that 1.x.x version and probably also in 1.6.2, the latest 1.x.x version available.

Alternatively, you can branch off of any version you like and modify it, or even start your very own.

I am having trouble understanding where the flu comes into play, but I sure hope this is not COVID-19 related.
