### ISSUE TITLE
hanging on pingSevers

### ISSUE THREAD

**Issue by diffsky** [ddsol/speedtest.net#12]
Initially found via https://github.com/sindresorhus/speed-test/issues/13#issuecomment-137872255, but also happening in the example README code. Seems like it gets stuck in the pingServers function. 

Changing https://github.com/ddsol/speedtest.net/blob/master/index.js#L260 to `<=todo` allows it to progress and return a result.

**Comment by ddsol** [comment]
This is not a solution. This code works normally fine, so it's not a off-by-one error. Also looking closely at that code this is not where the issue is. Errors and successes alike are counted towards `done`. Maybe `pingServer` doesn't return or something else is amiss.

The reason it works when you change the `<todo` to `<=todo` is because it'll just go ping another server so if one server is not responding it will simply not wait for it. That seems like an okay thing to do, except it makes it so in all cases one more server is pinged than requested. I don't think it's a good idea make the ping count 'advisory'.

If someone feels like implementing it, it would be easy to make `pingServer` itself time out with an error after 5 seconds. This would work great.

That said, I don't really have time to work on it now. I'll be happy to merge pull requests, though.

**Comment by diffsky** [comment]
Yeah I thought the code must have been that way and working for a while; just trying to pin down where it got stuck. I'll put up a PR for the timeout error.
