### ISSUE TITLE
Config event returns empty data

### ISSUE THREAD

**Issue by roman-turchenko** [ddsol/speedtest.net#19]
I noticed, that config event returns empty data like below:
{client:{}, times:{}, download:{}, upload:{}}

As I found, it happens because the request to the http://www.speedtest.net/speedtest-config.php returns following: http://prntscr.com/9v3q5c

Any Idea how to fix this?

**Comment by ddsol** [comment]
This should really produce an error. I think the error from Ookla should just be forwarded to the app and your app should do less testing per second.

**Comment by roman-turchenko** [comment]
Could you check please, is this issue reproduce from your side?
Because I have set 	console.log(data); exit(); to the getXML function (line №236) and I pretty sure that app does only one request per one one launch :-)

**Comment by ddsol** [comment]
I tried and can't repro it. I guess I could write an app to call it multiple times and I would be rate limited as well. But I haven't done that.

**Comment by clarkio** [comment]
I ran into this issue as well during the request for http://www.speedtest.net/speedtest-config.php. I was finding that when I don't specify a server to use and your library is left to calculate the server, it was not finding a valid option based on distance. I found that this was due to the `client` configuration data not being populated prior to your calculations for `distance`. After further debugging, I believe the speedtest.net service is throttling/blocking the default user-agent being used for your http request for http://www.speedtest.net/speedtest-config.php. When I change the user-agent to something else, the `client` options are populated and the library accurately determines the nearest server to use for the speed test.

For some context, I came across this when using the [speed-test cli](https://github.com/sindresorhus/speed-test) library which uses your speedtest.net library. In the speed-test cli library we do not specify a `serverId` option so your library is left to determine which server to use. When running through your calculations to determine that, since I am attempting to run via the cli there isn't a user-agent provided so your default user-agent is always used. Anyone running without a user-agent will be using the default one so it is quickly flagged by the speedtest.net service to be throttled/blocked and causing this issue.

I'm not sure what the best approach would be to resolve this right now, but I will give it some thought and post here if I come up with a good option. I am interested to hear your thoughts as well.

Adding @sindresorhus ([speed-test cli](https://github.com/sindresorhus/speed-test) author) in case Sindre has any thoughts on this as well.

**Comment by sindresorhus** [comment]
Can't we just use a randomly generated user-agent?

**Comment by clarkio** [comment]
Thanks for joining the discussion. Yes that is one option and I was able to successfully use the library that way in my tests of it.

The other option I was thinking is requiring the user of this library to always provide the user-agent. I've created a sample of how that might change the use of speed-test cli here: https://github.com/clarkio/speed-test/pull/1/files

**Comment by clarkio** [comment]
Something else that could possibly help is removing the need to get the client xml from http://www.speedtest.net/speedtest-config.php and instead store it. That way we don't overuse the speedtest.net service and avoid the throttling/blocking all together.

Just thinking of some possible options, but defer to you both on what would be best here.

I'd be happy to do the work for whatever solution is decided and contribute back.

**Comment by ddsol** [comment]
I think using a different foxed user agent copied from a well known browser may also do the trick. I am not for the user to provide the agent because it shifts more responsibility for providing a workouround onto the user when that's not necessary. A random US seems better.
Caching the configuration is an awesome idea also. It should be cleared if any ip addresses change.

**Comment by sindresorhus** [comment]
Yeah, using a browser user-agent would be better.

**Comment by clarkio** [comment]
Ok would it be alright if I issue a PR with just the change to the default user-agent for that particular request with the issue for now?

I'm thinking of just swapping it to the latest Chrome user-agent since, as @sindresorhus mentioned, a browser user-agent would be better. http://www.useragentstring.com/pages/Chrome/

Afterwards I could possibly follow up with another PR to provide a good caching implementation of the config data needed from speedtest.net.

**Comment by ddsol** [comment]
Well, it would of course be great if you whipped up a PR with a fix. Everyone likes fixes.
