### ISSUE TITLE
Linting issues

### ISSUE THREAD

**Issue by beau6183** [ddsol/speedtest.net#3]
I know it's a matter of taste, but I'm working on some speed reporting issues (consistently slower speeds from this tool being reported than what the speedtest.net interface reports), and the linting issues are just annoying me. Would you be opposed to me fixing up the formatting and such so that lint stops complaining? Obviously it would be in a pull request of its own as to not introduce new functionality on top.

**Comment by ddsol** [comment]
That sounds great. Personally, I don't use lint, because it complains too much about issues i don't even agree with. This is why I can't bring myself to bring my code in line with Crockford's opinion. I feel like I'm in an argument with the guy...

About the speed issues, I had seen someone else add in a factor of some kind elsewhere to bring it closer to the speedtest.net official numbers. Maybe Speedtest.net adds in a fudge factor that counts TCP headers and such also as bits (because technically, they are). Of course, I only measure data bytes sent successfully. I would not be opposed to adding in a fudge factor constant that would bring it close, as long as enough testing is done to pin this number down.

**Comment by ddsol** [comment]
I changed the code a bit. Results are now reported in Mbps (1 million bits per second). They are also adjusted to be in-line with speedtest.net results. See the new Readme (bottom) for more info.
