### ISSUE TITLE
upload test doesn't work on Linux

### ISSUE THREAD

**Issue by bprodoehl** [ddsol/speedtest.net#7]
I'm running Node 0.12.4 on OS X 10.10 and Fedora 22, and OS X is reporting somewhat believable upload numbers, but Fedora is reporting about 4Gbps (way too high, as if it is instantly assuming that all the data to be written was already written).

**Comment by ddsol** [comment]
This is because the module only counts how long it takes to send the data and it doesn't wait for a reply. In the case of large send buffers, this could significantly skew the results, as data isn't actually sent, but placed in an "outbox" instead, taking around 0 time.

I'll see what I can do to fix this.

**Comment by ddsol** [comment]
Cannot reproduce
