### ISSUE TITLE
Document "correction factor" methodology in README

### ISSUE THREAD

**Issue by jsejcksn** [ddsol/speedtest.net#79]
I see this comment:

https://github.com/ddsol/speedtest.net/blob/be216001d79176eea3a6b14e59f2782d0d7f86fd/index.js#L36

Perhaps you can provide in [README.md](https://github.com/ddsol/speedtest.net/blob/master/README.md) more detail about the methodology for deriving the correction factors so that others can understand exactly how and why these factors are used. This is extremely important for understanding the quality of information provided by this module.

**Comment by ddsol** [comment]
I am not guaranteeing in any way the quality or precision of the data produced by this module. The numbers are derived with a few tests ran over my own internet. They are fudge factors that won't hold up to scrutiny since the measuring method between SpeedTest and this module is just really different. If you have a problem with that, use the unfudged `originalUpload` and `originalDownload` numbers. They will, however, still be vastly different from what SpeedTest produces. If you want to know if it is being honest with the data or not, you can look at the source and see if you agree.

**Comment by jsejcksn** [comment]
@ddsol Your response makes me think I've offended you—I certainly didn't mean to, and I apologize if that's the case.

Reading the source is actually what inspired me to create this issue. Of course there are no accuracy guarantees—I realize that this module measures values differently than speedtest.net. My intention was to ask if you could provide greater detail about how you derived the correction factors in your testing so that I and others can understood how and why you arrived at those values since you include them.

**Comment by ddsol** [comment]
I divided what I got from ST and what I got from this module. I used averages over a statistically insufficient number of tests. The numbers should not be counted on. Consider them toy numbers (much like ST's numbers are toy numbers considering their statistically questionable methods).

**Comment by jsejcksn** [comment]
Thanks—this is exactly what I was looking for. I think that there are plenty of people who

- won't read the source
- won't even read the documentation
- will just copy + paste example code into their app

but for those who will take the time to at least read the readme, I think this is an important note. I've created a PR to include this information in the _considerations_ section. Feel free to edit if you are willing to accept it.
